version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Mount backend folder to /app inside the container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONBUFFERED=1
    env_file:
      - ./.env.dev # Load environment variables
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=escapadedb

volumes:
  postgres_data:
